version: "3"
services:
  strapi:
    image: strapi
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/usr/src/api
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypassword

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  nuxt:
    image: nuxt
    container_name: nuxt
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - strapi
